# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180417_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created',
            new_name='creat_ed',
        ),
    ]
