# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-17 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='creat_ed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
